Models/UserGroup.cs
using System.ComponentModel.DataAnnotations;

namespace UserManagement.Models
{
    public class UserGroup
    {
        [Key]
        public int UserGroupId { get; set; }

        public int UserId { get; set; }
        public Users Users { get; set; } = null!;

        public int GroupId { get; set; }
        public Groups Groups { get; set; } = null!;
    }
}

Controllers/UserGroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UserManagement.Models;
using UserManagement.DTOs;

namespace UserManagement.Controllers
{
    public class UserGroupsController : Controller
    {
        private readonly UserManagementContext _context;

        public UserGroupsController(UserManagementContext context)
        {
            _context = context;
        }

        // GET: UserGroups
        public async Task<IActionResult> Index()
        {
            var userManagementContext = _context.UserGroups.Include(u => u.Groups).Include(u => u.Users);
            return View(await userManagementContext.ToListAsync());
        }

        // GET: UserGroups/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.UserGroups == null)
            {
                return NotFound();
            }

            var userGroup = await _context.UserGroups
                .Include(u => u.Groups)
                .Include(u => u.Users)
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (userGroup == null)
            {
                return NotFound();
            }

            return View(userGroup);
        }

        // GET: UserGroups/Create
        public IActionResult Create()
        {
            ViewData["GroupId"] = new SelectList(_context.Groups, "GroupId", "GroupId");
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: UserGroups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UserGroupId,UserId,GroupId")] UserGroup userGroup)
        {
            if (ModelState.IsValid)
            {
                _context.Add(userGroup);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["GroupId"] = new SelectList(_context.Groups, "GroupId", "GroupId", userGroup.GroupId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", userGroup.UserId);
            return View(userGroup);
        }

        // GET: UserGroups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.UserGroups == null)
            {
                return NotFound();
            }

            var userGroup = await _context.UserGroups.FindAsync(id);
            if (userGroup == null)
            {
                return NotFound();
            }
            ViewData["GroupId"] = new SelectList(_context.Groups, "GroupId", "GroupId", userGroup.GroupId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", userGroup.UserId);
            return View(userGroup);
        }

        // POST: UserGroups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("UserGroupId,UserId,GroupId")] UserGroup userGroup)
        {
            if (id != userGroup.UserId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(userGroup);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserGroupExists(userGroup.UserId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["GroupId"] = new SelectList(_context.Groups, "GroupId", "GroupId", userGroup.GroupId);
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", userGroup.UserId);
            return View(userGroup);
        }

        // GET: UserGroups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.UserGroups == null)
            {
                return NotFound();
            }

            var userGroup = await _context.UserGroups
                .Include(u => u.Groups)
                .Include(u => u.Users)
                .FirstOrDefaultAsync(m => m.UserId == id);
            if (userGroup == null)
            {
                return NotFound();
            }

            return View(userGroup);
        }

        // POST: UserGroups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.UserGroups == null)
            {
                return Problem("Entity set 'UserManagementContext.UserGroups'  is null.");
            }
            var userGroup = await _context.UserGroups.FindAsync(id);
            if (userGroup != null)
            {
                _context.UserGroups.Remove(userGroup);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        //GET:
        public async Task<IActionResult> UserCountPerGroup()
        {
            var groupUserCounts = await _context.Groups
                .Select(g => new GroupWithUserCount
                {
                    GroupName = g.GroupName,
                    UserCount = g.UserGroups.Count
                })
                .ToListAsync();

            return View(groupUserCounts);
        }


        public async Task<IActionResult> ListGroups()
        {
            var groups = await _context.Groups.ToListAsync();
            return View(groups);
        }

        //GET:
        public async Task<IActionResult> UsersByGroup(int? groupId)
        {
            if (groupId == null)
            {
                return NotFound();
            }

            var group = await _context.Groups.FindAsync(groupId);

            if (group == null)
            {
                return NotFound();
            }

            var usersInGroup = await _context.UserGroups
                .Where(ug => ug.GroupId == groupId)
                .Include(ug => ug.Users)
                .Select(ug => ug.Users)
                .ToListAsync();

            ViewData["GroupName"] = group.GroupName;
            return View(usersInGroup);
        }


        private bool UserGroupExists(int id)
        {
          return (_context.UserGroups?.Any(e => e.UserId == id)).GetValueOrDefault();
        }
    }
}

Views/UserGroups/Create.cshtml
@model UserManagement.Models.UserGroup

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>UserGroup</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="get">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <div class="form-group">
                <label asp-for="GroupId" class="control-label"></label>
                <select asp-for="GroupId" class ="form-control" asp-items="ViewBag.GroupId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Create">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/UserGroups/Delete.cshtml
@model UserManagement.Models.UserGroup

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>UserGroup</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserGroupId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserGroupId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Users)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Users.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Groups)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Groups.GroupId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="UserId" />
        <input type="hidden" asp-for="GroupId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/UserGroups/Details.cshtml
@model UserManagement.Models.UserGroup

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>UserGroup</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserGroupId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserGroupId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Users)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Users.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Groups)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Groups.GroupId)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Views/UserGroups/Edit.cshtml
@model UserManagement.Models.UserGroup

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>UserGroup</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserGroupId" class="control-label"></label>
                <input asp-for="UserGroupId" class="form-control" />
                <span asp-validation-for="UserGroupId" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="UserId" />
            <input type="hidden" asp-for="GroupId" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/UserGroups/Index.cshtml
@model IEnumerable<UserManagement.Models.UserGroup>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.UserGroupId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Users)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Groups)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UserGroupId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Users.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Groups.GroupId)
            </td>
            <td>
                    @Html.ActionLink("Edit", "Edit", new {@item.UserGroupId}) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

Views/UserGroups/ListGroups.cshtml
@model List<UserManagement.Models.Groups>

@{
    ViewData["Title"] = "List of Groups";
}

<h1>@ViewData["Title"]</h1>

<h4>Click on a group to show the users in that group</h4>
<ul>
    @foreach (var group in Model)
    {
        <li>
            <a href="@Url.Action("UsersByGroup", "UserGroups", new { groupId = group.GroupId })">@group.GroupName</a>
        </li>
    }
</ul>

Views/UserGroups/UserCountPerGroup.cshtml
@model List<UserManagement.DTOs.GroupWithUserCount>

@{
    ViewData["Title"] = "User Count per Group";
}

<h1>@ViewData["Title"]</h1>

<table class="table">
    <thead>
        <tr>
            <th>Group Name</th>
            <th>Number of Users</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var group in Model)
        {
            <tr>
                <td>@group.GroupName</td>
                <td>@group.UserCount</td>
            </tr>
        }
    </tbody>
</table>

Views/UserGroups/UsersByGroup.cshtml
@model List<UserManagement.Models.Users>

@{
    ViewData["Title"] = "Users in Group: " + ViewData["GroupName"];
}

<h1>@ViewData["Title"]</h1>

<table class="table">
    <thead>
        <tr>
            <th>User ID</th>
            <th>User Name</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model)
        {
            <tr>
                <td>@user.Id</td>
                <td>@user.Name</td>
            </tr>
        }
    </tbody>
</table>